# Generated by Django 4.1 on 2023-03-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_food_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='foodid',
        ),
    ]
